### PR TITLE
core: services: Add limit_ram_usage

### PR DESCRIPTION
**Pull request by patrickelectric**
Limit ram usage by python programs to 100MB

### CODE REVIEW

**Comment by Williangalvani** [comment]
what happens is the service hits the memory limit?

**Comment by patrickelectric** [comment]
> what happens is the service hits the memory limit?

The code raise a `MemoryLimit` exception

**Comment by Williangalvani** [comment]
I have mixed feelings here. I like the idea, but I think if should be further handled. should we have all services check for this exception?
or perhaps have it kill and restart them?

**Comment by Williangalvani** [comment]
some of them, like Kraken, are find, but I wonder about the basic funcionalities one, mostly the ones related to piloting/networking

**Comment by patrickelectric** [comment]
We are on master branch, the main point is for us to find where the ram problems are happening and logging it. 
For a stable release we can just remove or increase the limit.
Right now having it at least allow the system to recover. Otherwise the user looses the entire vehicle and a power reboot is necessary.

**Review by joaoantoniocardoso — APPROVED** [review]
I agree to have this. We might need to figure out the limits, but this could prevent the situation where a service triggers Linux's OOM killer, and the main process is killed, being unable to recover.

**Comment by Williangalvani** [comment]
fair enough, let's get it in. needs a rebase though

**Pull request merged**
