### PR TITLE
core: tools: mavlink2rest: Update to t0.11.19

### PR DESCRIPTION
**Pull request by patrickelectric**
For more information: https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.19

### CODE REVIEW

**Comment by rafaellehmkuhl** [comment]
The BlueOS image is not appearing for me.

**Review by joaoantoniocardoso — APPROVED** [review]
I don't know exactly what to test. BlueOS seems to be working normally.

**Review by rafaellehmkuhl — APPROVED** [review]
I'm testing here with my PR and the buttons2 + s/t axes are appearing correctly in the `MANUAL_CONTROL` messages. Besides that, commands are working fine.

**Comment by ES-Alexander** [comment]
"What's new" docs should specify that 1.2 adds support for the extended `MANUAL_CONTROL` protocol (extra axes? + buttons), e.g. for firmwares like recent ArduSub.

**Pull request merged**
