### PR TITLE
install: fix configuration of config.txt

### PR DESCRIPTION
**Pull request by Williangalvani**
this should make blueos_startup_update stop running in the first boot.

I have a following patch that adds tests of blueos_startup_update and bcm_27xx to our pre push hook tests

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
This improvement seems a bit easy to break: every time we update the startup update script, we'd have actually to check if the boot happens, somehow.

Couldn't we import and use the startup update functions directly?

**Comment by Williangalvani** [comment]
> This improvement seems a bit easy to break: every time we update the startup update script, we'd have actually to check if the reboot happens, somehow.
> 
> Couldn't we import and use the startup update functions directly?

it wont be breakable after my tests get in, but yes, that is an interesting idea, I'll play with it

**Comment by Williangalvani** [comment]
I think we should probably go with this minimal patch for 1.2.x and refactor the whole thing to use blueos_startup_update for master

**Pull request merged**
