### PR TITLE
Change logfile name

### LINKED ISSUE #2969: bug: logfile zip does not extract on Windows
### Bug description

When downloading system logs in Windows, the produced file gives repeated errors like "Error 0x80070057: The parameter is incorrect". I believe this is because the logfiles use `:` (colon) as a delimiter, which is disallowed on Windows.

image

### Steps to reproduce

1. Download System Logs to Windows.
2. Right click on file and choose "Extract All"

### Primary pain point(s)

_No response_

### Additional context

_No response_

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

### PR DESCRIPTION
**Pull request by rotu**
1. Remove dividers - these are unnecessary and the colon causes problems (fixes #2969)
2. Switch order from month,day,year to year,month,day. This ensures correct collation when sorted

### CODE REVIEW

**Review by patrickelectric — COMMENTED** [review]
@voorloopnul @joaoantoniocardoso can this be a problem ?

**Comment by joaoantoniocardoso** [comment]
> @voorloopnul @joaoantoniocardoso can this be a problem ?

Definitely. Symbols are problematic for file names in general, and Windows is especially restrict about that.

**Comment by patrickelectric** [comment]
@joaoantoniocardoso I'm talking about the log filename format itself. Changes will need to happen in our rust and cloud projects, no ?

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso I'm talking about the log filename format itself. Changes will need to happen in our rust and cloud projects, no ?

Oh. MCM has a windows compatible filename, but also uses `-` as date separator.

**Comment by rotu** [comment]
`-` is fine in a filename. I just removed it because I thought it didn't really serve a purpose and having both `_` and `-` seemed messy.

I considered some variations like:
`logfile_2024-12-31_23-59-59.log`
`logfile-20241231-235959.log`
`logfile_20241231T235959.log`
`20241231_235959.log`

And I wound up liking `logfile_20241231_235959.log` best.

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
