### PR TITLE
Fix tour

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
```
Error: Could not resolve './components/vue-tour/dist/vue-tour.css' from src/main.ts
```

**Comment by patrickelectric** [comment]
@joaoantoniocardoso can you replicate the same error locally ? I'm having a bad time trying to figure out why CI is failing.

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso can you replicate the same error locally ? I'm having a bad time trying to figure out why CI is failing.

yes. I'll DM you

**Comment by patrickelectric** [comment]
@joaoantoniocardoso should be fixed now, thanks for helping!

**Review by joaoantoniocardoso — APPROVED** [review]

**Pull request merged**
