### PR TITLE
core: services: helper: main: Add some header properties

### PR DESCRIPTION
**Pull request by patrickelectric**
This allows it to work with cockpit vite development server

Tested with #2401 

image

### CODE REVIEW

**Comment by Williangalvani** [comment]
that is wild. do you know _why_ this fixes the issue?

**Comment by joaoantoniocardoso** [comment]
> that is wild. do you know _why_ this fixes the issue?

The _why_ is beyond my understandings, but I believe this is coming from what Patrick got from the Requests library, which defines its default as:

```Python
from urllib3.util import make_headers, parse_url

# Ensure that ', ' is used to preserve previous delimiter behavior.
DEFAULT_ACCEPT_ENCODING = ", ".join(
    re.split(r",\s*", make_headers(accept_encoding=True)["accept-encoding"])
)

def default_user_agent(name="python-requests"):
    """
    Return a string representing the default user agent.

    :rtype: str
    """
    return f"{name}/{__version__}"

def default_headers():
    """
    :rtype: requests.structures.CaseInsensitiveDict
    """
    return CaseInsensitiveDict(
        {
            "User-Agent": default_user_agent(),
            "Accept-Encoding": DEFAULT_ACCEPT_ENCODING,
            "Accept": "*/*",
            "Connection": "keep-alive",
        }
    )
```

The [make_headers from urllib3](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.make_headers) will give `‘gzip,deflate’`.

**Comment by patrickelectric** [comment]
> > that is wild. do you know _why_ this fixes the issue?
> 
> The _why_ is beyond my understandings, but I believe this is coming from what Patrick got from the Requests library, which defines its default as:
> 
> ```python
> from urllib3.util import make_headers, parse_url
> 
> # Ensure that ', ' is used to preserve previous delimiter behavior.
> DEFAULT_ACCEPT_ENCODING = ", ".join(
>     re.split(r",\s*", make_headers(accept_encoding=True)["accept-encoding"])
> )
> 
> def default_user_agent(name="python-requests"):
>     """
>     Return a string representing the default user agent.
> 
>     :rtype: str
>     """
>     return f"{name}/{__version__}"
> 
> def default_headers():
>     """
>     :rtype: requests.structures.CaseInsensitiveDict
>     """
>     return CaseInsensitiveDict(
>         {
>             "User-Agent": default_user_agent(),
>             "Accept-Encoding": DEFAULT_ACCEPT_ENCODING,
>             "Accept": "*/*",
>             "Connection": "keep-alive",
>         }
>     )
> ```
> 
> The [make_headers from urllib3](https://urllib3.readthedocs.io/en/stable/reference/urllib3.util.html#urllib3.util.make_headers) will give `‘gzip,deflate’`.

Yep, it was from the requests lib, I used Wireshark and found out that the header was necessary.

**Review by joaoantoniocardoso — APPROVED** [review]
Can we add a note that this is using the default headers from Requests as the reference?

**Pull request merged**
