### PR TITLE
core: start-blueos-core: add python bin path to PATH

### LINKED ISSUE #2508: Error flashing Pixhawks: Uploader binary not found on systems PATH
image

### PR DESCRIPTION
**Pull request by Williangalvani**
fix #2508

### CODE REVIEW

**Comment by Williangalvani** [comment]
nope, doesn`t fix it

**Comment by Williangalvani** [comment]
This approach works.
It does show up in the terminal sessions though, which isnt great.
setenv doesnt work for PATH for some reason.

**Comment by patrickelectric** [comment]
@Williangalvani can't we add it here ?
https://github.com/bluerobotics/blueos/blob/4806e1ad499a2bf07b353954e876707056bb904e/core/Dockerfile#L79

**Comment by Williangalvani** [comment]
> @Williangalvani can't we add it here ? https://github.com/bluerobotics/blueos/blob/4806e1ad499a2bf07b353954e876707056bb904e/core/Dockerfile#L79

HAh! I knew we had some sort of rcfile somewhere. I'll give it a try

**Comment by Williangalvani** [comment]
@patrickelectric looks good now! you can test both with `printenv` or just `ardup <tab>` and it autocompletes

**Review by patrickelectric — APPROVED** [review]
Nice job!

**Comment by patrickelectric** [comment]
> Nice job!

@Williangalvani should we cherry pick to stable ?

**Comment by Williangalvani** [comment]
> > Nice job!
> 
> @Williangalvani should we cherry pick to stable ?

yes, definitely

**Pull request merged**
