### PR TITLE
[Wizard] Fix return button

### LINKED ISSUE #2415: Wizard: Return button (on step 3) is going back to step 1 instead of previous step

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
closes #2415

### CODE REVIEW

**Review by patrickelectric — CHANGES_REQUESTED** [review]
It appears to be not working.
The third has a missing prefix (core: frontend:...).
Peek 2024-02-27 08-34

**Comment by Williangalvani** [comment]
> It appears to be not working. The third has a missing prefix (core: frontend:...). Peek 2024-02-27 08-34 [ Peek 2024-02-27 08-34 ](https://private-user-images.githubusercontent.com/1215497/308151238-b025666b-a0c2-459e-b911-70ecc754e0cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDk0MzksIm5iZiI6MTcwOTA0OTEzOSwicGF0aCI6Ii8xMjE1NDk3LzMwODE1MTIzOC1iMDI1NjY2Yi1hMGMyLTQ1OWUtYjkxMS03MGVjYzc1NGUwY2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTU1MjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg5YmFjNzZhOGMwY2FkNGZhYTFjMjhjNTNjMDU3NzQxNDRmMDUwZjVlNmE0OGNhYTk4MTM2NGU2NmQ2N2JhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nRvIibBfI3CB1tsvVRCpJpwhXmUzBhYVNbm78NCLaVY) [ ](https://private-user-images.githubusercontent.com/1215497/308151238-b025666b-a0c2-459e-b911-70ecc754e0cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDk0MzksIm5iZiI6MTcwOTA0OTEzOSwicGF0aCI6Ii8xMjE1NDk3LzMwODE1MTIzOC1iMDI1NjY2Yi1hMGMyLTQ1OWUtYjkxMS03MGVjYzc1NGUwY2MuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMTU1MjE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg5YmFjNzZhOGMwY2FkNGZhYTFjMjhjNTNjMDU3NzQxNDRmMDUwZjVlNmE0OGNhYTk4MTM2NGU2NmQ2N2JhZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nRvIibBfI3CB1tsvVRCpJpwhXmUzBhYVNbm78NCLaVY)

my god what is happening to your computer?

**Comment by joaoantoniocardoso** [comment]
@patrickelectric can you check again? It is working here:

https://github.com/bluerobotics/BlueOS/assets/5920286/ddcf6133-bff0-4089-9c09-4d278cd0815b

**Comment by joaoantoniocardoso** [comment]
ping @patrickelectric

**Review by patrickelectric — APPROVED** [review]

**Pull request merged**
