### PR TITLE
core: bag-of-holdings: Disable CORS policy

### PR DESCRIPTION
**Pull request by rafaellehmkuhl**
This patch allows external applications, like Cockpit, to use the service to store configuration data.

### CODE REVIEW

**Comment by Williangalvani** [comment]
have you tried going through /bag/ ? nginx should handle it

**Comment by rafaellehmkuhl** [comment]
> have you tried going through /bag/ ? nginx should handle it

Tried, yes. No success.

**Comment by rafaellehmkuhl** [comment]
> have you tried going through /bag/ ? nginx should handle it

I took a look at our nginx file and there's no CORS policy configuration.

**Comment by rafaellehmkuhl** [comment]
@Williangalvani @patrickelectric any suggestion on this one?

**Comment by Williangalvani** [comment]
can you try adding both of these to the "server" block?
https://github.com/bluerobotics/BlueOS/blob/master/core/tools/nginx/nginx.conf#L132-L135

**Comment by Williangalvani** [comment]
or maybe we just need `proxy_hide_header` on /bag

**Comment by rafaellehmkuhl** [comment]
> or maybe we just need `proxy_hide_header` on /bag

No luck.

I really think the server has to add CORS policy.
NGINX can do so much. In terms of delivering the content or not is up to the actual server (FastAPI/Starlette/Uvicorn).

**Pull request merged**
