### PR TITLE
core: tools: linux2rest: Update to v0.5.4

### PR DESCRIPTION
**Pull request by patrickelectric**
This new version follows the same log structure as mavlink-camera-manager and also allows the user to log custom system information

### CODE REVIEW

**Review by joaoantoniocardoso — CHANGES_REQUESTED** [review]
1. We need to update the command-line to add the log settings in the PR, without it, it'll just not run.

I was testing with `--log-system netstat=10,platform=10,serial-ports=10,system-cpu=10,system-disk=30,system-info=10,system-memory=10,system-network=10,system-process=10,system-temperature=10,system-unix-time-seconds=10`

2. The BlueOS system-information frontend seems to be failing to get the temperature:
image

3. Keep in mind that CPU peaks might be a little high for the max frequencies:

https://github.com/bluerobotics/BlueOS/assets/5920286/aa352f05-801a-4fff-93ff-d3b5733f9c50

4. The .log (wrongly named) contains no logged data, just warn/info messages.

**Comment by patrickelectric** [comment]
@joaoantoniocardoso the filename should be fixed now.
But, I want to do the tunning of the logging system in following PRs.

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso the filename should be fixed now. But, I want to do the tunning of the logging system in following PRs.

I meant.. if we merge this as it was, there would be no linux2rest running. It was panicking

**Comment by patrickelectric** [comment]
@joaoantoniocardoso thanks for pointing, indeed it was crashing. This final version should have everything fixed.

**Review by joaoantoniocardoso — APPROVED** [review]

**Pull request merged**
