### PR TITLE
BlueOS: Update to use mavlink2rest to 0.11.18

### PR DESCRIPTION
**Pull request by patrickelectric**
Change logs:
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.18
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.17
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.16
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.15
- https://github.com/mavlink/mavlink2rest/releases/tag/t0.11.14

### CODE REVIEW

**Comment by patrickelectric** [comment]
> Please fix the commit message: it mentions Cargo, but it's actually about the binary already built.
> 
> About the change, it's breaking BlueOS.
> 
> From the autopilot service logs:
> 
> ```shell
> commonwealth.mavlink_comm.exceptions.MavlinkMessageReceiveFail: Received status code of 404.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
> 2023-11-27 18:16:11.175 | INFO     | uvicorn.protocols.http.h11_impl:send:461 - 127.0.0.1:55950 - "GET /v1.0/vehicle_type HTTP/1.0" 500                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
> 2023-11-27 18:16:12.223 | ERROR    | commonwealth.utils.apis:custom_route_handler:36 - Unhandled service exception.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
> 2023-11-27 18:16:12.224 | ERROR    | commonwealth.utils.apis:custom_route_handler:37 - Received status code of 404.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
> Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
>   File "/home/pi/services/ardupilot_manager/main.py", line 272, in <module>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>     loop.run_until_complete(server.serve())                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>     │    │                  │      └ <function Server.serve at 0xb5c70ec8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
>     │    │                  └ <uvicorn.server.Server object at 0xb54aa838>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
>     │    └ <function BaseEventLoop.run_until_complete at 0xb63c9c40>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>     └ <_UnixSelectorEventLoop running=True closed=False debug=False>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
>     self.run_forever()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
>     │    └ <function BaseEventLoop.run_forever at 0xb63c9bf8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
>     └ <_UnixSelectorEventLoop running=True closed=False debug=False>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>     self._run_once()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>     │    └ <function BaseEventLoop._run_once at 0xb63ca9b8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>     └ <_UnixSelectorEventLoop running=True closed=False debug=False>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
>     handle._run()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
>     │      └ <function Handle._run at 0xb64156a0>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
>     └ <Handle <TaskStepMethWrapper object at 0xb41fe388>()>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
>     self._context.run(self._callback, *self._args)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>     │    │            │    │           │    └ <member '_args' of 'Handle' objects>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>     │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0xb41fe388>()>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
>     │    │            │    └ <member '_callback' of 'Handle' objects>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
>     │    │            └ <Handle <TaskStepMethWrapper object at 0xb41fe388>()>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
>     │    └ <member '_context' of 'Handle' objects>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>     └ <Handle <TaskStepMethWrapper object at 0xb41fe388>()>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>   File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>     result = await app(self.scope, self.receive, self.send)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>                    │   │    │      │    │        │    └ <function RequestResponseCycle.send at 0xb5413c88>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
>                    │   │    │      │    │        └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb41c1d60>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
>                    │   │    │      │    └ <function RequestResponseCycle.receive at 0xb5413cd0>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
>                    │   │    │      └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb41c1d60>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
>                    │   │    └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
>                    │   └ <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb41c1d60>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>                    └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb544daf0>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
>   File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/proxy_headers.py", line 45, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>     return await self.app(scope, receive, send)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
>                  │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb41c1d60>>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
>                  │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.h11_impl.RequestResponseCycle object at 0xb41c1d60>>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
>                  │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>                  │    └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb54aa8c8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
>                  └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0xb544daf0>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
>   File "/usr/local/lib/python3.9/site-packages/uvicorn-0.13.4-py3.9.egg/uvicorn/middleware/message_logger.py", line 61, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
>     await self.app(scope, inner_receive, inner_send)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>           │    │   │      │              └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb4b46850>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
>           │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
>           │    └ <fastapi.applications.FastAPI object at 0xb558aaf0>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>           └ <uvicorn.middleware.message_logger.MessageLoggerMiddleware object at 0xb54aa8c8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>   File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
>     await super().__call__(scope, receive, send)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
>                            │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb4b46850>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
>                            │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>                            └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>     await self.middleware_stack(scope, receive, send)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
>           │    │                │      │        └ <function MessageLoggerMiddleware.__call__.<locals>.inner_send at 0xb4b46850>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
>           │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
>           │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
>           │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb558ac28>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
>           └ <fastapi.applications.FastAPI object at 0xb558aaf0>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
>     await self.app(scope, receive, _send)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
>           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb4b46418>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>           │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
>           │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb558ab80>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
>           └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb558ac28>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
>     await self.app(scope, receive, sender)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
>           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46388>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
>           │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
>           │    └ <fastapi.routing.APIRouter object at 0xb558ab50>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
>           └ <starlette.exceptions.ExceptionMiddleware object at 0xb558ab80>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
>     await route.handle(scope, receive, send)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
>           │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46388>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
>           │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
>           │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
>           │     └ <function Mount.handle at 0xb5e39928>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
>           └ <starlette.routing.Mount object at 0xb54a3a48>                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 376, in handle                                                                                             
>     await self.app(scope, receive, send)                                                                                                                                                                         
>           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46388>                                                                                                       
>           │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                
>           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                            
>           │    └ <fastapi.applications.FastAPI object at 0xb54a3a78>                           
>           └ <starlette.routing.Mount object at 0xb54a3a48>                                                                                                                                                       
>   File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/applications.py", line 199, in __call__                                                                                          
>     await super().__call__(scope, receive, send)                                                                                                                                                                 
>                            │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46388>                                                                                                                                                                                                           
>                            │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                        
>                            └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                    
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/applications.py", line 111, in __call__                                                                                                                                 
>     await self.middleware_stack(scope, receive, send)                                                                                                                                                            
>           │    │                │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46388>                                                                                          
>           │    │                │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                   
>           │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                           
>           │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb54a3e50>                                                                                                                                                                   
>           └ <fastapi.applications.FastAPI object at 0xb54a3a78>                                                               
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/middleware/errors.py", line 159, in __call__                                                                                                                            
>     await self.app(scope, receive, _send)                                                                                                                                                                                                                   
>           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0xb4b46148>                                                                                                                                                 
>           │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                                 
>           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                        
>           │    └ <starlette.exceptions.ExceptionMiddleware object at 0xb54a3e38>                                                                                                                                                                            
>           └ <starlette.middleware.errors.ServerErrorMiddleware object at 0xb54a3e50>                     
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/exceptions.py", line 71, in __call__                                                                                                                                    
>     await self.app(scope, receive, sender)                                                                                                                                                                                                                  
>           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46b20>                                                                                                                                                                                                                   
>           │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                      
>           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                        
>           │    └ <fastapi.routing.APIRouter object at 0xb54a3988>                                                                                                                                                 
>           └ <starlette.exceptions.ExceptionMiddleware object at 0xb54a3e38>                                                                                                                                       
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 566, in __call__                                                                                                                                                                                                       
>     await route.handle(scope, receive, send)                                                                                                                                                                      
>           │     │      │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46b20>                                                                                                    
>           │     │      │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                                                                                                                             
>           │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                    
>           │     └ <function Route.handle at 0xb5e39190>                                                                                                                                                           
>           └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb54d15e0>                     
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 227, in handle                                                                                              
>     await self.app(scope, receive, send)                                                                                                                                                                          
>           │    │   │      │        └ <function ExceptionMiddleware.__call__.<locals>.sender at 0xb4b46b20>                                                                                                        
>           │    │   │      └ <function MessageLoggerMiddleware.__call__.<locals>.inner_receive at 0xb4b46bf8>                                                                                                      
>           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.1'}, 'http_version': '1.0', 'server': ('127.0.0.1', 8000), 'cl...                                                                                                                                                                        
>           │    └ <function request_response.<locals>.app at 0xb54884a8>                                                                                                                                           
>           └ <commonwealth.utils.apis.GenericErrorHandlingRoute object at 0xb54d15e0>                     
>   File "/usr/local/lib/python3.9/site-packages/starlette-0.13.6-py3.9.egg/starlette/routing.py", line 41, in app                                                                                                  
>     response = await func(request)                                                                                                                                                                                
>                      │    └ <starlette.requests.Request object at 0xb54aab98>                                                                                                                                     
>                      └ <function GenericErrorHandlingRoute.get_route_handler.<locals>.custom_route_handler at 0xb5488460>                                                                                                                                                                                                    
> > File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/utils/apis.py", line 31, in custom_route_handler                                                                                                                                                                                    
>     return await original_route_handler(request)                                                                                                                                                                  
>                  │                      └ <starlette.requests.Request object at 0xb54aab98>              
>                  └ <function get_request_handler.<locals>.app at 0xb5488388>                                                                                                                                      
>   File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 201, in app                                                                                                     
>     raw_response = await run_endpoint_function(                                                                                                                                                                   
>                          └ <function run_endpoint_function at 0xb5e34028>                                                                                                                                         
>   File "/usr/local/lib/python3.9/site-packages/fastapi-0.63.0-py3.9.egg/fastapi/routing.py", line 148, in run_endpoint_function                                                                                                                                                                                              
>     return await dependant.call(**values)                                                                                                                                                                         
>                  │         │      └ {}                                                                                                                                                                            
>                  │         └ <function get_vehicle_type at 0xb5488340>                                                                                                                                            
>                  └ <fastapi.dependencies.models.Dependant object at 0xb54d1748>                          
>                                                                                    
>                                                                                                         
>   File "/home/pi/services/ardupilot_manager/main.py", line 126, in get_vehicle_type                                                                                                                               
>     return await autopilot.vehicle_manager.get_vehicle_type()                                            
>                  │         │               └ <function VehicleManager.get_vehicle_type at 0xb571bb68>                                                                                                             
>                  │         └ <commonwealth.mavlink_comm.VehicleManager.VehicleManager object at 0xb54bbbc8>                                                                                                       
>                  └ <ArduPilotManager.ArduPilotManager object at 0xb54bb928>                                                                                                                                       
>                                                                                                          
>   File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/mavlink_comm/VehicleManager.py", line 75, in get_vehicle_type                                                                                                                                                                       
>     heartbeat_message = await self.mavlink2rest.get_updated_mavlink_message("HEARTBEAT")                                                                                                                          
>                               │    │            └ <function MavlinkMessenger.get_updated_mavlink_message at 0xb571b928>                                                                                                                                                                                                      
>                               │    └ <commonwealth.mavlink_comm.MavlinkComm.MavlinkMessenger object at 0xb558a538>                                                                                                
>                               └ <commonwealth.mavlink_comm.VehicleManager.VehicleManager object at 0xb54bbbc8>                                                                                                    
>   File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/mavlink_comm/MavlinkComm.py", line 114, in get_updated_mavlink_message                                                   
>     first_message = await self.get_mavlink_message(message_name, vehicle or self.system_id, component)   
>                           │    │                   │             │          │    │          └ 1          
>                           │    │                   │             │          │    └ 1                                                                                                                              
>                           │    │                   │             │          └ <commonwealth.mavlink_comm.MavlinkComm.MavlinkMessenger object at 0xb558a538>                                                                                                                                                                  
>                           │    │                   │             └ None                                                                                                                                           
>                           │    │                   └ 'HEARTBEAT'                                                                                                                                                  
>                           │    └ <function MavlinkMessenger.get_mavlink_message at 0xb571b8e0>                                                                                                                    
>                           └ <commonwealth.mavlink_comm.MavlinkComm.MavlinkMessenger object at 0xb558a538>                                                                                                                                                                                                                    
>   File "/usr/local/lib/python3.9/site-packages/commonwealth-0.1.0-py3.9.egg/commonwealth/mavlink_comm/MavlinkComm.py", line 70, in get_mavlink_message                                                                                                                                                                       
>     raise MavlinkMessageReceiveFail(f"Received status code of {response.status}.")                                                                                                                                
>           └ <class 'commonwealth.mavlink_comm.exceptions.MavlinkMessageReceiveFail'>                     
>                                                                                                                                           
> ```

Thanks, should be fixed by 0.11.16, I just did the release

**Comment by joaoantoniocardoso** [comment]
> Thanks, should be fixed by 0.11.16, I just did the release

Great, now it seems to be working fine!

But again, the commit message doesn't make much sense for this repository as we don't use Cargo.

**Review by rafaellehmkuhl — CHANGES_REQUESTED** [review]
I think we need to use the --default, right?

**Comment by patrickelectric** [comment]
> I think we need to use the --default, right?

it already sets v1 as default, by default.

**Comment by rafaellehmkuhl** [comment]
Version of m2r is appearing as 0.11.15.

**Comment by patrickelectric** [comment]
Yes, I moved as a draft for now until I fix some problems related to actix sharing global scope

**Comment by rafaellehmkuhl** [comment]
The m2r page is also not being ablle to fetch it's own endpoints (it's returning 404).

**Comment by patrickelectric** [comment]
> The m2r page is also not being ablle to fetch it's own endpoints (it's returning 404).

That's a problem related to actix with the global scope as well

**Comment by Williangalvani** [comment]
this link is broken, you can easily fix it by using a relative path:
image

This one looks like it wasn't updated after an api change:
image
image

**Comment by patrickelectric** [comment]
> this link is broken, you can easily fix it by using a relative path: image
> 
> This one looks like it wasn't updated after an api change: image image

I believe that feature is broken since added on BlueOS. To access it is necessary to use the absolute path of the extension over accessing it via available services. That's irrelevant to this PR, that just adds the latest modifications for cockpit.

I'm also open for suggestions of how to fix the websocket connection for redirected extensions.

**Comment by joaoantoniocardoso** [comment]
[Cargo: Update to use mavlink2rest to 0.11.17](https://github.com/bluerobotics/BlueOS/pull/2200/commits/97496d761b228f680ab17654f340eae1cb0714ef)

@patrickelectric can you fix this commit message? We don't have cargo here.

**Comment by patrickelectric** [comment]
> [Cargo: Update to use mavlink2rest to 0.11.17](https://github.com/bluerobotics/BlueOS/pull/2200/commits/97496d761b228f680ab17654f340eae1cb0714ef)
> 
> @patrickelectric can you fix this commit message? We don't have cargo here.

Ops, sorry about that, fixed.

**Comment by patrickelectric** [comment]
> this link is broken, you can easily fix it by using a relative path: image
> 
> This one looks like it wasn't updated after an api change: image image

I'll take a second look to see if it's easy to fix.

**Review by Williangalvani — APPROVED** [review]

**Pull request merged**
