### PR TITLE
Ardupilot udp serial port fix

### LINKED ISSUE #2627: "udpclient:ip:pport" serial settings do not work in ArdupilotManager
The correct setting is "udp" and not "udpclient"

### PR DESCRIPTION
**Pull request by Williangalvani**
Screenshot 2024-05-24 at 11 36 55

fix #2627

### CODE REVIEW

**Comment by joaoantoniocardoso** [comment]
nothing like a consistent API :)

**Comment by joaoantoniocardoso** [comment]
so, Ardupilot Manager here doesn't need to use the same description names as MAVLink endpoint types (see the class EndpointType above)?

**Review by patrickelectric — APPROVED** [review]

**Review by patrickelectric — CHANGES_REQUESTED** [review]
It appears that there is indeed an inconsistent as pointed by @joaoantoniocardoso

**Comment by Williangalvani** [comment]
> so, Ardupilot Manager here doesn't need to use the same description names as MAVLink endpoint types (see the class EndpointType above)?

that is correct, these are not "Mavlink Endpoints". They are often not mavlink at all.

These are the serial port commandline arguments taken by ardupilot. which are [udp, udpin, tcp].
The ardupilot code code be updated to also take `udpout`, but that would only take effect in a future release.

**Pull request merged**
