### PR TITLE
core: autopilot manager: bump memory limit to 200mb

### LINKED ISSUE #2170: Autopilot Manager runs out of memory when decompressing the firmware manifest
Screenshot 2023-10-16 at 15 57 14

### PR DESCRIPTION
**Pull request by Williangalvani**
fix #2170

### CODE REVIEW

**Comment by Williangalvani** [comment]
autopilotmanager idles at ~ 25mb, the unzipped manifest file is 36mb. loading the whole thing as json in memory seems to be what is causing the large memory usage.
We can either merge this or try to find a better json parser.

**Review by patrickelectric — APPROVED** [review]
The issue in the end is having both in memory at the same time. We can let it go since it happens only once with the manifest decompression.

**Comment by patrickelectric** [comment]
For more information:
[memray-flamegraph-output.html.zip](https://github.com/bluerobotics/BlueOS/files/13035094/memray-flamegraph-output.html.zip)

**Comment by Williangalvani** [comment]
possibly relevant further on
https://pythonspeed.com/articles/json-memory-streaming/

**Comment by patrickelectric** [comment]
In the end the problem was with gzip and not the json, @Williangalvani you can check the flamegraph plot.

**Pull request merged**
