### PR TITLE
core: tools: mavlink2rest: Update to use t0.11.14

### PR DESCRIPTION
**Pull request by patrickelectric**
changelog: https://github.com/patrickelectric/mavlink2rest/releases/tag/t0.11.14

### CODE REVIEW

**Comment by rafaellehmkuhl** [comment]
Strange. The image is not appearing for me in BlueOS. Is your repo auto-uploading the docks?

**Comment by patrickelectric** [comment]
> Strange. The image is not appearing for me in BlueOS. Is your repo auto-uploading the docks?

it was not rebased over a python fix in CI, it should be available now in the next hour.

**Comment by rafaellehmkuhl** [comment]
> > Strange. The image is not appearing for me in BlueOS. Is your repo auto-uploading the docks?
> 
> it was not rebased over a python fix in CI, it should be available now in the next hour.

Still not appearing :(

**Review by rafaellehmkuhl — CHANGES_REQUESTED** [review]
image

The problem persists @patrickelectric.

**Comment by joaoantoniocardoso** [comment]
@patrickelectric is this PR still relevant?

**Pull request closed without merging**
