### PR TITLE
core: frontend: components: wizard: Add 'remind me later' when skipping wizard

### LINKED ISSUE #2330: Add a remind me later when asking to update to new version

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #2330 

image

### CODE REVIEW

**Comment by Williangalvani** [comment]
I think it would be better if it was just an independent button. while this is obvious, it... _feels_ weird.

**Comment by patrickelectric** [comment]
> I think it would be better if it was just an independent button. while this is obvious, it... _feels_ weird

Adding a third button just for that is kind of weird to me, this way we enforce the user to indeed disable the checkbox, make it more clear what he's doing.

**Comment by joaoantoniocardoso** [comment]
btw, _DON'T SHOW AGAIN_ seems conflicting with _Remind me later_

**Comment by patrickelectric** [comment]
> btw, _DON'T SHOW AGAIN_ seems conflicting with _Remind me later_
> 
> Maybe by positioning the checkbox below the _SKIP WIZARD_ button, it would look more like two separate groups (the _skip_ vs the _don't show_)?

That's why it's near the skip button. Putting in the bottom makes the entire thing weird with a space underneath.

**Comment by patrickelectric** [comment]
@Williangalvani @joaoantoniocardoso changed to add a second dialog to be more clear.

**Comment by ES-Alexander** [comment]
I don't think this needs to be documented - it's pretty obvious what the buttons do, so documentation would basically just be repeating the description that's included in the popup.

**Pull request merged**
