### PR TITLE
core: Dockerfile: Update blueos-base to v0.2.0

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Comment by Williangalvani** [comment]
MCM seems to be unhappy:
image

**Comment by patrickelectric** [comment]
Should be fixed by https://github.com/mavlink/mavlink-camera-manager/pull/404

**Comment by patrickelectric** [comment]
@Williangalvani check now, the latest version is based in master that provides the latest version of mcm

**Review by Williangalvani — APPROVED** [review]
looks good. I couldn't t test the cameras but that seems to be a hardware issue on my end

**Pull request merged**
