### PR TITLE
Refactor and add missing aarch64 binaries

### LINKED ISSUE #2671: [Tracking] Add missing aarch64 binaries
bridges
- [x] binary is available: https://github.com/patrickelectric/bridges/pull/14
- [ ] added to BlueOS

filebrowser
- [x] binary is available: [yes, since 2.29.0](https://github.com/filebrowser/filebrowser/releases/download/v2.30.0/linux-386-filebrowser.tar.gz)
- [ ] added to BlueOS

linux2rest
- [x] binary is available: [yes](https://github.com/patrickelectric/linux2rest/releases/download/v0.6.0/linux2rest-aarch64-unknown-linux-gnu)
- [ ] added to BlueOS

machineid-cli
- [x] binary is available: https://github.com/patrickelectric/machineid-cli/pull/1
- [ ] added to BlueOS

mavlink_camera_manager
- [x] binary is available: [yes](https://github.com/mavlink/mavlink-camera-manager/releases/download/t3.13.1/mavlink-camera-manager-aarch64)
- [x] added to BlueOS: https://github.com/bluerobotics/BlueOS/pull/2669

mavlink_router
- [x] binary is available: [yes](https://github.com/mavlink-router/mavlink-router/releases/download/v4/mavlink-routerd-glibc-aarch64)
- [x] added to BlueOS: #2684

mavlink2rest
- [x] binary is available: https://github.com/mavlink/mavlink2rest/pull/106
- [x] added to BlueOS: https://github.com/bluerobotics/BlueOS/pull/2672

mavp2p
- [x] binary is available: [yes](https://github.com/bluenviron/mavp2p/releases/download/v1.2.1/mavp2p_v1.2.1_linux_arm64v8.tar.gz)
- [ ] added to BlueOS

ttyd
- [x] binary is available: [yes](https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64)
- [ ] added to BlueOS

### PR DESCRIPTION
**Pull request by joaoantoniocardoso**
~Merge after #2677~

Closes #2671 

Note about some versions upgrade:
- filebrowser: `v2.24.2` -> `v2.30.0`
- bridges: `0.10.1` -> `0.10.2`
- machineid: `0.2.1` -> `0.2.2`

### CODE REVIEW

**Comment by patrickelectric** [comment]
@joaoantoniocardoso is this still in draft ? Can you rebase it ?

**Comment by patrickelectric** [comment]
Also.. is there a reason for this to be based over #2677 ?

**Comment by joaoantoniocardoso** [comment]
> Also.. is there a reason for this to be based over #2677 ?

just because I couldn't test it with the pre-push locally, but let's give it a try.

**Comment by joaoantoniocardoso** [comment]
@patrickelectric 

```Bash
ARCH="$(uname -m)"
case "$ARCH" in
  x86_64 | amd64)
    BUILD_NAME="foo"
    ;;
  armv6l | armv7l | armhf)
    BUILD_NAME="foo"
    ;;
  aarch64 | arm64)
    BUILD_NAME="foo"
    ;;
  *)
    echo "Architecture: $ARCH is unsupported, please create a new issue on https://github.com/bluerobotics/BlueOS/issues"
    exit 1
    ;;
esac
```

is this architecture match pattern okay? Should we use something broader like `arm64*` instead of just `arm64`?

**Comment by patrickelectric** [comment]
> @patrickelectric
> 
> ```shell
> ARCH="$(uname -m)"
> case "$ARCH" in
>   x86_64 | amd64)
>     BUILD_NAME="foo"
>     ;;
>   armv6l | armv7l | armhf)
>     BUILD_NAME="foo"
>     ;;
>   aarch64 | arm64)
>     BUILD_NAME="foo"
>     ;;
>   *)
>     echo "Architecture: $ARCH is unsupported, please create a new issue on https://github.com/bluerobotics/BlueOS/issues"
>     exit 1
>     ;;
> esac
> ```
> 
> is this architecture match pattern okay? Should we use something broader like `arm64*` instead of just `arm64`?
> 
> another question is if we can always mix armv6l, armv7l, armhf, or if it depends on how the software was built

That's a great question, but We should be fine to use match pattern. In theory, we should be fine by using armv7 and armhf in the same match, but I'm not that sure about armv6.

**Comment by joaoantoniocardoso** [comment]
> > @patrickelectric
> > ```shell
> > ARCH="$(uname -m)"
> > case "$ARCH" in
> >   x86_64 | amd64)
> >     BUILD_NAME="foo"
> >     ;;
> >   armv6l | armv7l | armhf)
> >     BUILD_NAME="foo"
> >     ;;
> >   aarch64 | arm64)
> >     BUILD_NAME="foo"
> >     ;;
> >   *)
> >     echo "Architecture: $ARCH is unsupported, please create a new issue on https://github.com/bluerobotics/BlueOS/issues"
> >     exit 1
> >     ;;
> > esac
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is this architecture match pattern okay? Should we use something broader like `arm64*` instead of just `arm64`?
> > another question is if we can always mix armv6l, armv7l, armhf, or if it depends on how the software was built
> 
> That's a great question, but We should be fine to use match pattern. In theory, we should be fine by using armv7 and armhf in the same match, but I'm not that sure about armv6.

[It seems to be compatible](http://single-boards.com/armv6-vs-armv7/), but I can't test it..

**Review by patrickelectric — APPROVED** [review]

**Comment by patrickelectric** [comment]
@joaoantoniocardoso be free to merge

**Pull request merged**
