### PR TITLE
Move major tom to 1.1

### PR DESCRIPTION
**Pull request by patrickelectric**

### CODE REVIEW

**Review by Williangalvani — APPROVED** [review]
code looks good, we should test with @voorloopnul to make sure it is ok, possibly. up to you two.

**Comment by patrickelectric** [comment]
ping @voorloopnul

**Comment by ES-Alexander** [comment]
Can we add a setting or button to disable it?
Ideally we'd have detailed settings, but a single bag variable or something is likely sufficient at the moment. I don't like the message it sends to add a telemetry system that we don't allow turning off.

**Review by voorloopnul — APPROVED** [review]
All looking good!
There are 50 vehicles running this code already, so I'm ok with moving it forward.

**Comment by voorloopnul** [comment]
> All looking good! There are 50 vehicles running this code already, so I'm ok with moving it forward.

**Comment by voorloopnul** [comment]
@Williangalvani @patrickelectric @rjehangir 
One question tho,  since we will be using the Cloud integration as an extension,  wouldn't it be better to have the telemetry living there? There are some code that will potentially serve both codebases.

Also, as a non-intrusive code, we can likely benefit from independent updates.

**Comment by patrickelectric** [comment]
I do agree with that.

**Comment by patrickelectric** [comment]
@Williangalvani can you sign the cla ?

**Comment by Williangalvani** [comment]
> @Williangalvani can you sign the cla ?

Wait what. I did it a long time ago

**Comment by patrickelectric** [comment]
> > @Williangalvani can you sign the cla ?
> 
> Wait what. I did it a long time ago

The CLA was updated.

**Comment by Williangalvani** [comment]
> > > @Williangalvani can you sign the cla ?
> > 
> > 
> > Wait what. I did it a long time ago
> 
> The CLA was updated.

done

**Comment by ES-Alexander** [comment]
Feature was removed before being in a stable release, so no need for docs.

**Pull request merged**
